[aws]
aws_region_name = us-east-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = default
update_check = true
sanity_check = true

[cluster default]
key_name = cpe512
base_os = alinux2
cluster_type = ondemand
scheduler = sge
# Regular option
# compute_instance_type = c4.large
# Heavy computing option
compute_instance_type = c5.24xlarge
vpc_settings = default
desired_vcpus = 4
# Regular option
# max_vcpus = 64
# Heavy computing option
max_vcpus = 64

[vpc default]
vpc_id = vpc-04b6a270a5d0390e6
master_subnet_id = subnet-02f1c2a3c487c2663
compute_subnet_id = subnet-094b770b1c30f7d00
use_public_ips = false
